import Head from 'next/head';
import Image from 'next/image';
import styles from './styles.module.css';
import { Navbar, Button } from "../../components";
import Wrapper from "../../components/Wrapper/index";
import PackageCard from "./_packagecard";
import LocationCard from "./_locationcard"
import data from "./content.json";
import { useState } from 'react';
import ActivityCard from './_activitycard';
import QuoteForm from './_quoteForm';
import useGetVisibility from "../api/_useGetVisibility";

const options = {
    root: null,
    rootMargin: "0px",
    threshold: 0.3
};
export default function Book() {
    const [custom, changeCustom] = useState(false);
    const [location, updateLocation] = useState("");
    const [activities, changeActivity] = useState([]);
    const [visible, ref] = useGetVisibility(options);
    console.log(data["packages"])
    return (
        <>
            <Head>
                <title>Book a Flight</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Wrapper>
                <Navbar />
                <h1>Choose a Package</h1>
                <h2>Pick an Existing Package</h2>
                <div className={styles.bookBack} />
                <div className={styles.cardGrid} ref={ref}>
                    {data["packages"].map((value, index) => (
                        <PackageCard
                            key={`package-${index}`}
                            title={value.title}
                            description={value.description}
                            location={value.location}
                            stars={value.stars}
                            img={value.img}
                            price={value.price}
                            changeCustom={changeCustom}
                            show={visible}
                        />
                    ))}
                </div>
                {custom &&
                    <>
                        <h2 style={{ marginTop: "10px", marginBottom: "10px" }}>
                            Customize:
                        </h2>
                        <h3 style={{ marginTop: "10px", marginBottom: "10px" }}>
                            Select a Destination:
                        </h3>
                        <div className={styles.cardGrid}>
                            {data["locations"].map((value, index) => (
                                <LocationCard
                                    key={`location-${index}`}
                                    title={value.title}
                                    description={value.description}
                                    img={value.img}
                                    price={value.price}
                                    time={value.time}
                                    active={location == value.title}
                                    onClick={() => updateLocation(value.title)}
                                />
                            ))}
                        </div>
                        <h3 style={{ marginTop: "10px", marginBottom: "10px" }}>
                            Select Your Activities:
                        </h3>
                        <div className={styles.cardGrid}>
                            {data["activities"][location].map((value, index) => (
                                <ActivityCard
                                    key={`activity-${location}-${index}`}
                                    title={value.title}
                                    age={value.age}
                                    description={value.description}
                                    img={value.img}
                                    alt={value.alt}
                                    cost={value.cost}
                                    time={value.time}
                                    active={activities.includes(index)}
                                    onClick={() => changeActivity(prev => {
                                        if (prev.includes(index)) {
                                            return prev.filter(val => val != index);
                                        }
                                        else {
                                            return [...prev, index]
                                        }
                                    })} />
                            ))}
                            {location == "" ? "Please select a location to select your activities" : ""}
                        </div>
                        <h3 style={{ marginTop: "10px", marginBottom: "10px" }}>
                            Get A Quote:
                        </h3>
                        <QuoteForm />
                    </>
                }
            </Wrapper>
        </>
    )
}