import Head from 'next/head';
import Image from 'next/image';
import styles from './styles.module.css';
import { Navbar, Button } from "../../components";
import Wrapper from "../../components/Wrapper/index";
import PackageCard from "./_packagecard";
import data from "./content.json";

export default function Book() {
    return (
        <>
            <Head>
                <title>Book a Flight</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Wrapper>
                <Navbar/>
                <h1>
                    Choose a Package
                </h1>
                <h2>
                    Pick an Existing Package
                </h2>
                <div className={styles.cardGrid}>
                    {data["packages"].map((value, index) => (
                        <PackageCard
                            key={`package-${index}`}
                            title={value.title}
                            description={value.description}
                            location={value.location}
                            stars={value.stars}
                            img={value.img}
                            price={value.price}
                            />
                    ))}
                </div>
            </Wrapper>
        </>
    )
}