import { useRouter } from "next/router";
import Head from "next/head";
import Link from "next/link";
import Wrapper from "../../../components/Wrapper/index";
import { Navbar, Icon, Footer, DatePicker, Counter, Button } from "../../../components";
import styles from "./styles.module.css";
import dataset from "./content.json";
import Image from "next/image";
import Tabs from "./_tabs";
import { useContext, useEffect, useState } from "react";
import Details from "./_details";
import Journey from "./_journey";
import Gallery from "./_gallery";
import activityData from "../content.json";
import Vehicles from "./_vehicles";
import { UserContext } from "../../api/_userContext";

export default function ProductDetail() {
    const router = useRouter();
    const packageName = router.query.package;
    const [tab, changeTab] = useState("Details");
    const { changeCurrentOrder } = useContext(UserContext);
    const [peopleCount, changePeopleCount] = useState(0);
    const [date, changeDate] = useState(new Date());

    if (Object.keys(dataset).indexOf(packageName) == -1) {
        return (
            <>
                <Wrapper>
                    <Navbar />
                    <h4>404 Error: The page you were looking for doesn&apos;t exist </h4>
                    <Link style={{ color: "#FFFFFF" }} href="/packages">
                        Back to Packages
                    </Link>
                </Wrapper>
            </>
        );
    }

    const handleSubmit = () => {
        changeCurrentOrder({
            count: peopleCount,
            date: date,
            type: packageName
        });
        router.push("/checkout");
    }

    const data = dataset[packageName];
    const gallery = data["gallery"];
    let activities = [];
    data.activities.forEach(type => {
        activities = [...activities, ...activityData.activities[type]];
    });


    return (
        <>
            <Head>
                <title>Package Details</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Wrapper>
                <Navbar />
                <h1>{packageName}</h1>
                <div className={styles.picsAndText}>
                    <div className={styles.checkoutPrompt}>
                        <div style={{ display: "flex", flexDirection: "column", gap: "10px", alignItems: "flex-start" }}>
                            <span style={{ display: "flex", alignItems: "baseline" }}><h2>${data.cost.toLocaleString()}</h2><p><strong>/person</strong></p></span>
                            <h3>Select Date and Travelers</h3>
                            <p className="caption">DATE</p>
                            <DatePicker
                                startDate={date}
                                endDate={new Date(date.getFullYear() + 1, date.getMonth(), date.getDate())}
                                setDate={() => { }}
                            />
                            <p className="caption">ADULTS</p>
                            <Counter
                                count={peopleCount}
                                updateCount={changePeopleCount}
                            />
                            <Button background="light" onClick={handleSubmit}>Proceed to Checkout</Button>
                        </div>
                        <div>
                            <p>* Prices are based off of 2150 projections.</p>
                            <p>** Dates are subject to change.</p>
                            <p>
                                <strong>Please note: </strong> all availability is first come
                                first serve and all prices are in USD before taxes.
                            </p>
                        </div>
                    </div>
                    <Gallery images={gallery} />
                </div>
                <div style={{ display: "flex", flexDirection: "column", gap: "20px", marginBottom: "2rem" }}>
                    <h3>Offered Activities</h3>
                    <div style={{ display: "flex", gap: "20px", overflowX: "scroll" }}>
                        {activities.map(act => (
                            <div key={act.title} className={styles.activityCard}>
                                <Image src={act.img} alt={act.alt} fill />
                                <div>
                                    <h4>{act.title}</h4>
                                    <p>${act.cost.toLocaleString()}</p>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
                <Tabs
                    tab={tab}
                    changeTab={changeTab}
                    options={["Details", "Journey", "Vehicles"]}
                />
                {tab == "Details" && <Details />}
            </Wrapper >
            <>
                {tab == "Vehicles" && (
                    <Vehicles vehicles={data.vehicles} />
                )}
                {tab == "Journey" && <Journey packageName={packageName} />}
            </>
            <Footer />
        </>
    );
}

