import Link from "next/link";
import { Navbar, Wrapper, Footer } from "../../components";
import styles from "./aboutStyles.module.css";
import Head from "next/head";

export default function About() {
    return (
        <>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Wrapper>
                <Navbar />
                <h1>About</h1>
                <div className={styles.about}>
                    <h3>Statement of Originality</h3>
                    <p>To ensure a seamless, fast, and optimized user experience, this website uses <Link href="https://nextjs.org/" locale={false} target="_blank">Vercel&apos;s NextJS</Link> framework,
                        a <Link href="https://reactjs.org/" locale={false} target="_blank">ReactJS</Link> technology as the coding technology. However, the design system and brand themes are all
                        original and specially designed with the user&apos;s experience and accessibility in mind.
                    </p>
                    <p><strong>All Icons were created by the SpaceOasis team. </strong></p>
                </div>
                <div className={styles.links}>
                    <Link href="/static/CopyrightChecklist.pdf" locale={false} target="_blank">Copyright Checklist</Link>
                    <Link href="/static/SignedWorkLog.pdf" locale={false} target="_blank">Signed Plan of Work Log</Link>
                </div>
            </Wrapper>
        </>
    )
}