import Head from 'next/head'
import Image from 'next/image'
import styles from './home.module.css';
import { Navbar, Button } from "../components";
import Wrapper from "../components/Wrapper/index";
import PackageCard from "./book/_packagecard"

export default function Home() {
  return (
    <>
      <Head>
        <title>Space Oasis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <Navbar />
        <section id="hero" className={styles.hero}>
          <div className={styles.waterMark}>
            <p >Explore</p>
          </div>
          <div className={styles.heroText}>
            <h5>Explore Beyond the Confines of Your Existence</h5>
            <Button size="regular">Hello</Button>
          </div>
          <div className={styles.img}>
            <Image
              src={"/static/HeroImg.jpg"}
              fill
              alt="Soyuz Rocket Launches from Baiknor Launch Pad"
            />
          </div>
        </section>
        <section className={styles.promotion}>
          <h1>Find a Venture</h1>
          <div className={styles.cardGrid}>
            <PackageCard
              title="Lunar Exploration"
              img="/static/HeroImg.jpg"
              description="Lorem ipsum dolor sit amet consectetur. Lectus montes enim sem curabitur elit pretium commodo."
              price={450}
              location="The moon"
              stars={4} />
          </div>
        </section>
      </Wrapper>
    </>
  )
}
