import Head from 'next/head'
import Image from 'next/image'
import styles from './home.module.css';
import { Navbar, Button } from "../components";
import Wrapper from "../components/Wrapper/index";
import PackageCard from "./book/_packagecard";
import getClasses from './api/_getClasses';
import useGetVisibility from './api/_useGetVisibility';

const promotions = [
  {
    title: "Lunar Exploration",
    img: "/static/HeroImg.jpg",
    description: "Lorem ipsum dolor sit amet consectetur. Lectus montes enim sem curabitur elit pretium commodo.",
    price: 450,
    location: "The moon",
    stars: 4
  },
  {
    title: "Lunar Exploration",
    img: "/static/HeroImg.jpg",
    description: "Lorem ipsum dolor sit amet consectetur. Lectus montes enim sem curabitur elit pretium commodo.",
    price: 450,
    location: "The moon",
    stars: 4
  }, {
    title: "Lunar Exploration",
    img: "/static/HeroImg.jpg",
    description: "Lorem ipsum dolor sit amet consectetur. Lectus montes enim sem curabitur elit pretium commodo.",
    price: 450,
    location: "The moon",
    stars: 4
  },
];

const gallery = [
  {
    src: "/static/Gallery/1.jpg",
    alt: "An astronaut in mars"
  },
  {
    src: "/static/Gallery/2.jpg",
    alt: "An astronaut in mars"
  }, {
    src: "/static/Gallery/3.jpg",
    alt: "An astronaut in mars"
  }, {
    src: "/static/Gallery/4.jpg",
    alt: "An astronaut in mars"
  }
]
const options = {
  root: null,
  rootMargin: "0px",
  threshold: 0.3
};
export default function Home() {
  const [heroVisible, heroRef] = useGetVisibility(options);
  const [promoVisible, promoRef] = useGetVisibility({
    root: null,
    rootMargin: "0px",
    threshold: 0.8
  });
  const renderPromo = promotions.map((promotion, i) => (
    <PackageCard
      {...promotion}
      key={i}
      show={promoVisible}
    />
  ));



  const renderGallery = gallery.map((img, i) => (
    <div key={"Gallery" + i} className={styles.galleryImg} >
      <img {...img} key={"Gallery" + i} style={{ width: "100%", height: "auto" }} />
    </div >
  ));

  return (
    <>
      <Head>
        <title>Space Oasis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <Navbar />
        <section id="hero" className={styles.hero}>
          {/* <div className={styles.waterMark}>
            <p >Explore</p>
          </div> */}
          <div className={styles.heroText}>
            <h5>Explore Beyond the Confines of Your Existence</h5>
            <Button size="regular">Hello</Button>
          </div>
          <div className={getClasses(styles.img, heroVisible ? styles.show : styles.hide)} ref={heroRef}>
            <Image
              src={"/static/HeroImg.jpg"}
              fill
              alt="Soyuz Rocket Launches from Baiknor Launch Pad"
            />
          </div>
        </section>
        <section className={styles.promotion}>
          <div className={styles.promoBacking} />
          <h1>Find a Venture</h1>
          <div className={styles.promoHeader}>
            <h2>Top Picks</h2>
            <p>See All</p>
          </div>
          <div className={styles.cardGrid} ref={promoRef}>
            {renderPromo}
          </div>
        </section>
        <section className={styles.gallery}>
          <h1>Gallery</h1>
          <div className={styles.galleryGrid}>
            {renderGallery}
          </div>
        </section>
      </Wrapper>
    </>
  )
}
