import Head from "next/head";
import { Footer, Icon, Navbar } from "../../components";
import Wrapper from "../../components/Wrapper";
import getClasses from '../api/_getClasses';
import styles from "./vehicles.module.css";
import { useState } from "react";
import { useRouter } from "next/router";
import content from "./content.json";

export default function VehicleSelect(props) {
    const vehicles = content['vehicles'];

    let router = useRouter();

    const redirect = (title) => {
        router.push(`/vehicles/${title}`)
    }

    return (
        <>
            <Head>
                <title>Vehicles</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Wrapper>
                <Navbar />
                <h1>Select A Vehicle</h1>
                <div className={styles.cardGrid}>
                    {vehicles.map((vehicle, index) => (
                        <div className={getClasses(styles[vehicle.css], styles.card)} key={index} onClick={() => redirect(vehicle.title)}>
                            <h3>{vehicle.company}</h3>
                            <h2>{vehicle.title}</h2>
                        </div>
                    ))}
                </div>
            </Wrapper>
        </>
    )
}