import Head from 'next/head';
import Image from 'next/image';
import styles from './styles.module.css';
import { Navbar, Button, Footer } from "../../components";
import Wrapper from "../../components/Wrapper/index";
import PackageCard from "./_packagecard";
import LocationCard from "./_locationcard"
import data from "./content.json";
import { useState } from 'react';
import ActivityCard from './_activitycard';
import QuoteForm from './_quoteForm';
import useGetVisibility from "../api/_useGetVisibility";

export default function Packages() {
    const [custom, changeCustom] = useState(false);
    const [location, updateLocation] = useState("");
    const [activities, changeActivity] = useState([]);

    const goTo = (url) => {
        const element = document.getElementById(url);
        if (element) {
            element.scrollIntoView({ behavior: "smooth" })
        }
    }

    return (
        <>
            <Head>
                <title>Packages</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Wrapper>
                <Navbar />
                <h1>Choose a Package</h1>
                <section id="existing">
                    <div className={styles.header}>
                        <h2>Pick an Existing Package</h2>
                        <Button size="regular" onClick={() => goTo("customize")}>Or Customize</Button>
                    </div>
                    <div className={styles.bookBack} />
                    <div className={styles.cardGrid}>
                        {data["packages"].map((value, index) => (
                            <PackageCard
                                key={`package-${index}`}
                                title={value.title}
                                description={value.description}
                                location={value.location}
                                stars={value.stars}
                                img={value.img}
                                price={value.price}
                                changeCustom={changeCustom}
                            />
                        ))}
                    </div>
                    <p>*Cost approximations based on 2150 projections</p>
                </section>
                <section id='customize' style={{ paddingTop: "15px" }}>
                    <div className={styles.header}>
                        <h2>Customize</h2>
                        <Button size="regular" onClick={() => goTo("existing")}>Existing Packages</Button>
                    </div>
                    <h3 style={{ marginTop: "10px", marginBottom: "10px" }}>
                        Select a Destination:
                    </h3>
                    <div className={styles.cardGrid}>
                        {data["locations"].map((value, index) => (
                            <LocationCard
                                key={`location-${index}`}
                                title={value.title}
                                description={value.description}
                                img={value.img}
                                price={value.price}
                                time={value.time}
                                active={location == value.title}
                                onClick={() => updateLocation(value.title)}
                            />
                        ))}
                    </div>
                    <h3 style={{ marginTop: "10px", marginBottom: "10px" }}>
                        Select Your Activities:
                    </h3>
                    <div className={styles.cardGrid}>
                        {data["activities"][location].map((value, index) => (
                            <ActivityCard
                                key={`activity-${location}-${index}`}
                                title={value.title}
                                age={value.age}
                                description={value.description}
                                img={value.img}
                                alt={value.alt}
                                cost={value.cost}
                                time={value.time}
                                active={activities.includes(index)}
                                onClick={() => changeActivity(prev => {
                                    if (prev.includes(index)) {
                                        return prev.filter(val => val != index);
                                    }
                                    else {
                                        return [...prev, index]
                                    }
                                })} />
                        ))}
                        {location == "" ? "Please select a location to select your activities" : ""}
                    </div>
                </section>
                <h3 style={{ marginTop: "20px" }}>
                    Get A Quote:
                </h3>
                <QuoteForm />
            </Wrapper>
            <Footer />
        </>
    )
}